name: Tests

on: [push, pull_request]

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-latest

    services:

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements.txt 

    - name: Run tests and collect coverage
      env:
        SECRET: $(openssl rand -hex 32)
        DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
        REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}
      run: |
        cd backend/
        alembic upgrade head
        python -m pytest --cov=./ --cov-report=xml
 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
