name: Tests

on: [push, pull_request]

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements.txt 

    - name: Run tests and collect coverage
      env:
        SECRET: ff4c1a100618949dfb5cf50ecf05cba7ab6431f90ab045fe
        DATABASE_URL_TEST: postgresql+psycopg2://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
      run: |
        cd backend/ && python -m pytest --cov=./ --cov-report=xml
 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
