name: Tests

on: [push, pull_request]

jobs:
  pytest:
    name: Run tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements.txt 

    - name: Run tests
      env:
        SECRET: ff4c1a100618949dfb5cf50ecf05cba7ab6431f90ab045fe
        ALGORITHM: HS256
        DB_TEST_DIALECT: postgresql
        DB_TEST_DRIVER: psycopg2
        DB_TEST_USERNAME: postgres
        DB_TEST_PASSWORD: postgres
        DB_TEST_HOST: localhost
        DB_TEST_NAME: postgres
      run: |
        pwd
        cd backend/
        pwd
        python -m pytest -s
 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
